### ISSUE TITLE
subscribe does not receive messages after failover to slave

### ISSUE THREAD

**Issue by sagiegurari** [ortoo/node-redis-sentinel#26]
I setup a pub sub via redis.
The pub and sub are different processes that use redis to communicate from the pub process to the sub process.
I setup in both processes the node-redis-sentinel in same manner where both get 3 endpoints (sentinal, master and slave).

at first everything works good.
when I shutdown the master redis process, the publish is able to continue publishing (at least no errors in the console).
The subscriber process also doesn't show any errors, but I get no new messages.

Do I need to listen to some failover event and do resubscribe or something similar? or is it supposed to be transparent?

By the way, i have another part of the code that connects to the master directly via node_redis and when master goes down, i do catch and see that error.

**Comment by jamessharp** [comment]
It should just work transparently. Sounds like something is going wrong. Can you give me a simple bit of code to repro?

**Comment by sagiegurari** [comment]
sorry, was too long ago, had to switch to haredis instead to continue.
