### ISSUE TITLE
High number of +sdown and -sdown alerts from Redis Sentinel

### ISSUE THREAD

**Issue by givan** [ortoo/node-redis-sentinel#28]
Hello,

We've been receiving very high number of +sdown and *shortly* (within a couple of seconds) after it -sdown messages. sdown is subjective down, and our Redis cluster is up and running and being able to respond. Has anyone experienced the same issue recently? What is the reason sdown message is sent by the sentinel (what could be the root cause)?

# Server
redis_version:2.8.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:8ef9bbd7e542f69f
redis_mode:sentinel
os:Linux 2.6.18-308.1.1.el5 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.5.4
process_id:13050
run_id:04637707dd0fca755b8c7c1ec829f8033a83ac8d
tcp_port:26379
uptime_in_seconds:7706320
uptime_in_days:89
hz:17
lru_clock:14331916

# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
master0:name=master,status=ok,address=ip:6379,slaves=1,sentinels=2

Thanks,
- George

**Comment by jamessharp** [comment]
Sorry - I have no idea - you should direct this question to the redis guys.
