### ISSUE TITLE
Duplicate subscribe after senti failover

### ISSUE THREAD

**Issue by StevenRoan** [ortoo/node-redis-sentinel#31]
Hi, we tracking an issue that  after the redis-sentinel finishes a failover process, our node-redis client receives duplicate event if the client subscribe to certain channel.

To reproduce this problem, we create 3 redis processes running on 3 different ports (6379, 6479, 6579), and executes following node process.

```
var redis = require('redis');
var redisSentinel = require('redis-sentinel');
var EventEmitter = require('events').EventEmitter;

var sentinelConfig = {
    "sentinels": [{
        "host": "127.0.0.1",
        "port": 26379
    }, {
        "host": "127.0.0.1",
        "port": 26479
    }, {
        "host": "127.0.0.1",
        "port": 26579
    }],
    "masterName": "mymaster",
    "master_auth_pass": ""
};

var options = {
    master_auth_pass: sentinelConfig.master_auth_pass,
    return_buffers: true,
    role: 'master'
};

var client = redisSentinel.createClient(sentinelConfig.sentinels, sentinelConfig.masterName, options);

client.on("subscribe", function (channel, count) {
    console.log('[%s]Subscribe channel:%s', Date(), channel);
});

client.on('reconnecting', function () {
    console.log('[%s]Reconnecting', Date());
});

client.on('error', function () {
    console.log('[%s]Error', Date());
});

client.on("message", function (channel, message) {
    console.log("[%s]In channel: %s, receive msg: %s", Date(), channel, message);
});

client.subscribe('ch1');
```
Before failover, we publish in the master redis process (the one running on 6579) in redis-cli.

```
PUBLISH ch1 Hello6579
```

and we get correct output in the console as following.

```
[Mon Mar 02 2015 19:12:03 GMT+0800 (CST)]In channel: ch1, receive msg: Hello6579
```

Then, we start a failover process  by sentinel command and the master is switched to the redis process running on port 6479 then we publish similiar message. We get
```
[Mon Mar 02 2015 19:17:25 GMT+0800 (CST)]In channel: ch1, receive msg: Hello6479
[Mon Mar 02 2015 19:17:25 GMT+0800 (CST)]In channel: ch1, receive msg: Hello6479
```
One of the event is triggered by the redis client which connect to previous master (the one running on port 6579)

After trace the source code of both mranney/node_redis and this library, we found that the root cause is because the event listeners are not removed before we create a new client object and mount new listeners. This problem can be fixed by adding one line to cleaning all the event listeners before create a new connection as following.

```
            function refreshEndpoints() {
                client.connectionOption.port = "";
                client.connectionOption.host = "";
                client.stream.removeAllListeners(); /* This line */
                resolver(self.endpoints, masterName, function(_err, ip, port) {
                    if (_err) {
                        oldEmit.call(client, 'error', _err);
                    } else {
                        // Try reconnecting.
                        client.connectionOption.port = port;
                        client.connectionOption.host = ip;
                        client.connection_gone("sentinel induced refresh");
                    }
                });
            }
```
I am not sure this is the best way to solve it or not, just want to share this thought.

Thanks.

**Comment by thurmda** [comment]
We are seeing the same issue. Multiple events are fired after a fail over. When we test by failing over multiple times the number of duplicate events fired increases.

**Comment by jamessharp** [comment]
Thanks for everyone's help in this. Should now be fixed
