### ISSUE TITLE
standard way to test failover

### ISSUE THREAD

**Issue by ORESoftware** [ortoo/node-redis-sentinel#45]
Hi authors

Is there a standard way to test Redis-Sentinel using this library? How can we test the failover processes to see if everything is working as expected?

For example, from the bottom of this page:
http://objectrocket.com/blog/how-to/introduction-to-redis-sentinel

how can we execute this stuff:

```
If you’d like to receive some information about sentinel, simply run this command:

127.0.0.1:26379> INFO
This will give you information, such as who is the current master, how many slaves it has, and how many sentinels are monitoring it.

To test failover, simply execute:

127.0.0.1:26379> SENTINEL failover mymaster
```

**Comment by ORESoftware** [comment]
to get the info, I figured out the syntax, you just need client.info() like so:

```javascript
 client.info(function(err,res){   //can also be client.INFO()

                    if(callbackAlreadyInvoked === false){
                        callbackAlreadyInvoked = true;
                        if(err){
                            cb(err);
                        }else{
                            cb(null,res);
                        }
                    }
                });
```

but you would be doing us all a big favor if you could document the syntax for how to test failover. To show you how in the dark I am (feeling around), here is my best guess for the syntax to test failover (again, I just love guessing around).


```javascript
client.failover('mymaster_name',function(err,resp){


});
```

or is it

```javascript
client.SENTINEL.failover('mymaster_name',function(err,resp){


});
```

??? :(

**Comment by ORESoftware** [comment]
:( neither of those work, I feel stupid

**Comment by ORESoftware** [comment]
I looked through the code, both node-redid and this library, it doesn't look like you implemented the SENTINEL failover call. Is that right?

https://www.dropbox.com/s/i0bt6zuzfb3kd53/Screenshot%202015-06-19%2015.19.38.png?dl=0

**Comment by ORESoftware** [comment]
hullo?

**Comment by ORESoftware** [comment]
sorry, I was being a bit rude earlier - can you let me know if you understood my question or if you want me to clarify, thanks

**Comment by jamessharp** [comment]
From the [`node_redis` docs](https://github.com/mranney/node_redis#clientsend_commandcommand_name-args-callback) just use `.send_command` on a sentinel client. E.g.

```javascript
var sentinel = require('redis-sentinel');
var sentinelClient = sentinel.createClient(endpoints, {role: 'sentinel'});
sentinelClient.send_command('SENTINEL', ['failover', 'my master'], function(err, resp){});
```

**Comment by ORESoftware** [comment]
thanks I will give this a go
